apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-config
  namespace: exercises
data:
  MESSAGE: "Hello from the ConfigMap!"
  information.txt: "This is a sample text file stored in the ConfigMap."