apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-step3-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-step3
  template:
    metadata:
      labels:
        app: project-step3
    spec:
      containers:
        - name: project-step3-cont
          image: carlossss1011/project-step3