apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-app
  template:
    metadata:
      labels:
        app: project-app
    spec:
      containers:
        - name: project-app-container
          image: carlossss1011/project-app:1.02