apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-step4-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-step4
  template:
    metadata:
      labels:
        app: project-step4
    spec:
      containers:
        - name: project-step4-cont
          image: carlossss1011/project-step4