apiVersion: v1
kind: PersistentVolume
metadata:
  name: pingpong-logoutput-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/kube"